apiVersion: apps/v1
kind: Deployment
metadata:
  name: llmops-app
  labels:
    app: llmops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: llmops
  template:
    metadata:
      labels:
        app: llmops
    spec:
      containers:
      - name: llmops-container
        image: us-central1-docker.pkg.dev/mlops-thilina/llmops-project/llmops-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 5000
        envFrom:
          - secretRef:
              name: llmops-secrets # Pass the environment variables from the secret

---
apiVersion: v1
kind: Service
metadata:
  name: llmops-service
spec:
  type: LoadBalancer
  selector:
    app: llmops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000